Create get liquidation price
MetaBUILD-III/MetaBUILD_III_contracts pull request #11
Opened 2022-10-31 08:11 UTC by vlad-sundunchan

Добавил метод get_liquidation_price. Бизнес-логику не изменял. В сигнатуре метода есть параметры которые не используются. Данный метод работает только с одной парой usdt-wnear. 
Если нужно переделать бизнес-лгику то нужно будет решить пару вопросов.

2022-11-03 12:50 UTC, markblaize requested changes

2022-11-03 12:50 UTC, markblaize commented on src/price.rs
> +        (BigDecimal::from(buy_token_price) - (collateral_usd - BigDecimal::from(borrow_fee) * borrow_amount) / buy_amount + BigDecimal::from(sell_token_amount) * BigDecimal::from(swap_fee)).into()
@vlad-sundunchan 

calculation pseudo-code, pls ensure that all input parameters are used in correct dimension
```
collateral_usd = sell_token_amount * sell_token_price
position_amount_usd = collateral_usd * leverage 
volatility_rate = 95%
borrow_amount = collateral_usd * (leverage - 1)
buy_amount = position_amount_usd / buy_token_price

LP = (position_amount_usd - volatility_rate * collateral_usd + borrow_amount * borrow_fee + position_amount_usd * swap_fee) / buy_amount
```

interface
```
pub fn calculate_liquidation_price(
    sell_token_amount: U128,
    sell_token_price: Price,
    buy_token_price: Price,
    leverage: U128,
    borrow_fee: U128,
    swap_fee: U128,
) -> Price // ticker_id = usd
{
...
}
```

2022-11-03 12:50 UTC, markblaize commented on src/price.rs
> +    fn test_liquidation_price() {
@vlad-sundunchan, please use our calculations here https://docs.google.com/spreadsheets/d/194ero95KPezi2yvlq5I-BK5_Bowj2Vz75J6EOQzZq8s/edit?pli=1#gid=1392357925
to provide tests for each case

2022-11-04 11:41 UTC, TymofiiSavinov commented on src/lib.rs
> +            volatility_rate: BigDecimal::from(U128(95 * 10_u128.pow(22))),
change BigDecimal::from(U128(95 * 10_u128.pow(22))) => BigDecimal::from(95 * 10_u128.pow(22))

2022-11-04 11:41 UTC, TymofiiSavinov commented on src/lib.rs
> +        self.volatility_rate = BigDecimal::from(U128(rate.0 * 10_u128.pow(22)))
BigDecimal::from(rate.0)

2022-11-04 12:10 UTC, merged